import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#333b50',
        'surface-variant': '#d3e4fe',
        'tertiary': '#1e2539',
        'on-primary-fixed-variant': '#274e3d',
        'on-tertiary-fixed': '#131b2e',
        'on-surface': '#0b1c30',
        'inverse-primary': '#a5d0b9',
        'secondary-fixed-dim': '#ffb77d',
        'primary-fixed-dim': '#a5d0b9',
        'surface-container-low': '#eff4ff',
        'tertiary-fixed-dim': '#bec6e0',
        'tertiary-fixed': '#dae2fd',
        'secondary-container': '#fe932c',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'on-background': '#0b1c30',
        'error-container': '#ffdad6',
        'outline': '#717973',
        'primary': '#012d1d',
        'surface-container': '#e5eeff',
        'on-secondary-fixed': '#2f1500',
        'surface-container-highest': '#d3e4fe',
        'surface-bright': '#f8f9ff',
        'primary-container': '#1b4332',
        'on-error': '#ffffff',
        'error': '#ba1a1a',
        'surface-tint': '#3f6653',
        'on-secondary': '#ffffff',
        'surface-dim': '#cbdbf5',
        'on-error-container': '#93000a',
        'secondary': '#904d00',
        'surface': '#f8f9ff',
        'on-surface-variant': '#414844',
        'on-tertiary-fixed-variant': '#3f465c',
        'inverse-on-surface': '#eaf1ff',
        'primary-fixed': '#c1ecd4',
        'secondary-fixed': '#ffdcc3',
        'on-primary-fixed': '#002114',
        'inverse-surface': '#213145',
        'background': '#f8f9ff',
        'outline-variant': '#c1c8c2',
        'on-secondary-fixed-variant': '#6e3900',
        'on-tertiary-container': '#9ea5be',
        'surface-container-high': '#dce9ff',
        'on-primary-container': '#86af99',
        'on-secondary-container': '#663500',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        base: '8px',
        md: '16px',
        'margin-mobile': '16px',
        lg: '24px',
        xs: '4px',
        sm: '8px',
        xl: '40px',
        gutter: '24px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
